{
  "ipp": {
    "responseHeaders": {
      "Cache-Control": "public, max-age=2592000",
      "Access-Control-Allow-Origin":  "*"
    },
    "singleImageGallery": false,
    "singleItemAutoOpen": true,
    "downloadOriginalPhoto": true,
    "showGalleryTitle": true,
    "allowDownloadAll": 0,
    "showHomePage": false,
    "showGalleryTitle": true,
    "showMetadata": {
      "description": true
    },
    "customInvalidResponse": false
  },
  "lightGallery": {
    "controls": true,
    "download": true,
    "enableSwipe": true,
    "mobileSettings": {
      "controls": false,
      "showCloseIcon": true,
      "download": true
    }
  }
}
